### ISSUE TITLE
[New ADR]: KAS-FLEET-MANAGER Permissions Check API 

### ISSUE THREAD

**Issue by ziccardi** [bf2fc6cc711aee1a0c2a/architecture#48]
### What
We need to write a new ADR about a _Permissions Check API_ for the KAS-FLEET-MANAGER.
Such API will be similar to the `oc canI` api and will allow the caller to query the fleet manager about what he can or can't do and why.

### Why
Currently the only way to know if an action is allowed or not is by trying and checking the outcome.
Some of our APIs consumer (for example, the UI) needs to know upfront making the call if the call will be successful or not (to enable buttons, populate comboboxes, sliders, etc.): that means that without a permission API, they have to replicate **exactly** the same checks we already do in KAS-FLEET-MANAGER and every time something changes into the KAS-FLEET-MANAGER, they have to update their code accordingly.

### How
The _Permissions Check API_ should be something like this:

```
    /can/{verb}/{resource}
```
where `verb` will be the action and `resource` will be the _resource_ affected by the _action_.

The output of the call will be a json containing an `outcome` (granted or denied) and some details:

- if the outcome is `granted`, the detail will describe what has been granted
- it the outcome is `denied`, the detail will contain a list of errors describing what the user miss to be able to perform the action

#### Create Kafka

```
GET /can/create/kafka
```

**Granted Outcome:**
```json
{
   "outcome":"granted",
   "details":{
      "plans":[
         "standard.x1",
         "standard.x2",
         "eval.x1"
      ],
      "quota":{
         "granted":6,
         "available":4
      }
   }
}
```

**Denied Outcome - terms not accepted**
```json
{
   "outcome":"denied",
   "errors":[
      {
         "code":"ERR-001",
         "description":"Required terms have not been accepted",
         "metadata":[
            {
               "termsurl":"https://url.to.accept.terms"
            }
         ]
      }
   ]
}
```

**Comment by davidffrench** [comment]
@pmuir @emmanuelbernard What is the process for reviewing proposed ADRs. Creating an issue is called out in https://architecture.appservices.tech/about/adr-process but it does not advise on who or how these are reviewed.

**Comment by pmuir** [comment]
@tombentley ^^^

**Comment by pmuir** [comment]
I'd suggest dropping a note on the mailing list to start

**Comment by ziccardi** [comment]
@pmuir 
> I'd suggest dropping a note on the mailing list to start

mas-all?

**Comment by pmuir** [comment]
mas-architecture@redhat.com
