### ISSUE TITLE
Create customer exposed metric naming policy

### ISSUE THREAD

**Issue by JameelB** [bf2fc6cc711aee1a0c2a/architecture#61]
The current customer exposed metrics have inconsistent naming. There are currently two types of name format:
- recording rules (i.e. `kafka_topic:kafka_log_log_size:sum`)
   - This follows the format of \<level\>:\<metric name\>:\<aggregation\>
   - This makes sense when you know how it's implemented but it's an implementation detail.
- raw metrics (i.e. `kafka_controller_kafkacontroller_offline_partitions_count`).
   - This is taken directly from kafka metrics

We need to find a consistent logical naming scheme, bearing in mind that these metric names are an API and it's possible that the implementation of some of them may evolve over time.

We should create an ADR to define this policy. It should cover the following topics:
- How do we request new metrics?
- How do we name new metrics? 
- How would we deal with existing customer exposed metrics already available in our API?
- How can we version existing/new metrics?
- Competitive analysis, how are others doing this?

Related Epic: https://issues.redhat.com/browse/MGDSTRM-7080

**Comment by tombentley** [comment]
I can do this...

**Comment by tombentley** [comment]
I think this is really a platform wide concern. I.e. in general any managed service might expose a prometheus-scrapable endpoint to customers, and when doing so is creating a public API contract which therefore needs managing. Furthermore this could be handled in a consistent way across services. So I wonder if this should really be a AP, with a brief ADR which says "We're applying this pattern to the Kafka service". Wdyt @emmanuelbernard, @pmuir ?

**Comment by tombentley** [comment]
@JameelB I've added/reserved ADR-87 for now.

**Comment by JameelB** [comment]
Thank you @tombentley!

**Comment by emmanuelbernard** [comment]
Yes let’s have an AP

**Comment by JameelB** [comment]
@tombentley @emmanuelbernard created this PR to reserve ap-16 for this issue: https://github.com/bf2fc6cc711aee1a0c2a/architecture/pull/65
