### ISSUE TITLE
OpenAPI clients code generation - Kiota

### ISSUE THREAD

**Issue by andreaTP** [bf2fc6cc711aee1a0c2a/architecture#87]
Reference the [Original doc](https://docs.google.com/document/d/1WayfKKCvJn6gFmVRYbmBNTGixEF40vAMhdrlCDMLFuI/edit).

**Comment by andreaTP** [comment]
cc. @tombentley please assign this issue to me.

**Comment by tombentley** [comment]
@andreaTP it's an AP you want, right? (not an ADR)

**Comment by andreaTP** [comment]
Hi @tombentley , thanks for taking a look!

I'm finding it a little confusing to identify if I should submit an AP or an ADR.

Currently in the available documentation: https://github.com/bf2fc6cc711aee1a0c2a/architecture/blob/main/pages/about/index.adoc#architectural-pattern

I can see that, in the `AP` description, the term `ADR` is used interchangeably and I'm finding it hard to identify the key differences. Would you mind clarifying or directly suggesting the best curse of action?

**Comment by tombentley** [comment]
ADR records a decision (specific to a single service) that MUST be followed in applicable circumstances. The only way to avoid it is to supersede the decision.

PADR records a decision (applying to all services) that MUST be followed in applicable circumstances. The only way to avoid it is to supersede the decision.

Obviously these are a bit written-in-stone. So AP provides mechanism for saying "We think this is what we want to do, but we want to see whether the pattern is really generally applicable before we promote it to PADR". 

From the draft document you linked, I think this should be an AP. Once we've got experience with Kiota for at least one service we could have an PADR to record that it's what everyone MUST use from now on. 

Does that sound OK/work for you?

**Comment by andreaTP** [comment]
Thanks a ton for the clarification.

Yes, I'm fine with submitting it as an AP!

**Comment by andreaTP** [comment]
@tombentley the number given by the automation is colliding on @shawkins https://github.com/bf2fc6cc711aee1a0c2a/architecture/pull/82

**Comment by tombentley** [comment]
Sigh. Avoiding this kind of thing is why the automation allocates the id in an initial (basically empty) PR. It's not the fault of @shawkins for not knowing that (because the bot is only now working thanks to @grdryn). 

@andreaTP I'll bump your AP id manually. That should be enough to fix it for future APs too.

**Comment by tombentley** [comment]
@andreaTP you now have ADR 18 (you can re-fetch `main`).

**Comment by andreaTP** [comment]
Cool, thanks for sorting things out! I'll continue to work on `AP 18`
